import menu_01 from "../assets/menu/menu_01.jpg";
import menu_02 from "../assets/menu/menu_02.jpg";
import menu_03 from "../assets/menu/menu_03.jpg";
import menu_04 from "../assets/menu/menu_04.jpg";
import menu_05 from "../assets/menu/menu_05.jpg";
import menu_06 from "../assets/menu/menu_06.jpg";
import menu_07 from "../assets/menu/menu_07.jpg";
import menu_08 from "../assets/menu/menu_08.jpg";

export const menu = {
  "menuData":[{
      "id": 1,
      "image": {"path":menu_01, "text":"Chicken Parmesan"},
      "title": "Chicken Parmesan",
      "description": "Delicious Chicken Parmesanwith a blend of flavors.",
      "price": 9.99,
      "badge": "NEW",
      "tag": "nonveg",
    },
    {
      "id": 2,
      "image": {"path":menu_02, "text":"Baby Burguer"},
      "title": "Baby Burguer",
      "description": "Savory Baby Burguer with a hint of spice.",
      "price": 12.99,
      "badge": "HOT",
      "tag":"nonveg",
    },
    {
      "id": 3,
      "image": {"path":menu_03, "text":"Cucumber Juice"},
      "title": "Cucumber Juice",
      "description": "Mouthwatering Cucumber Juice with fresh ingredients.",
      "price": 8.99,
      "badge": null,
      "tag": "drinks",
    },
    {
      "id": 4,
      "image": {"path":menu_04, "text":"Kiwi Frozen Yogurt"},
      "title": "Kiwi Frozen Yogurt",
      "description": "A classic Kiwi Frozen Yogurt with a modern twist.",
      "price": 14.99,
      "badge": "NEW",
      "tag": "dessert",
    },
    {
      "id": 5,
      "image": {"path":menu_05, "text":"Grilled Salmon"},
      "title": "Grilled Salmon",
      "description": "A delightful dish 5 bursting with flavors.",
      "price": 10.99,
      "badge": null,
      "tag": "nonveg",
    },
    {
      "id": 6,
      "image": {"path":menu_06, "text":"Greek Moussaka"},
      "title": "Greek Moussaka",
      "description": "Spicy Greek Moussaka with a perfect balance of heat.",
      "price": 11.99,
      "badge": "HOT",
      "tag":"vegetarian"
    },
    {
      "id": 7,
      "image": {"path":menu_07, "text":"Hot Dog"},
      "title": "Hot Dog",
      "description": "A hearty Hot Dog that will fill you up.",
      "price": 13.99,
      "badge": null,
      "tag": "starters",
    },
    {
      "id": 8,
      "image": {"path":menu_08, "text":"Patatas Rellenas"},
      "title": "Patatas Rellenas",
      "description": "A light Patatas Rellenas that is perfect for lunch.",
      "price": 9.99,
      "badge": null,
    },
    {
      "id": 9,
      "image": {"path":menu_04, "text":"Kiwi Frozen Yogurt"},
      "title": "Kiwi Frozen Yogurt",
      "description": "A light Kiwi Frozen Yogurt that is perfect for lunch.",
      "price": 9.99,
      "badge": null,
      "tag": "dessert",
    },
    {
      "id": 10,
      "image": {"path":menu_05, "text":"Grilled Salmon"},
      "title": "Grilled Salmon",
      "description": "Satisfying Grilled Salmon with a touch of elegance.",
      "price": 14.99,
      "badge": null,
      "tag": "nonveg",
    },
    {
      "id": 11,
      "image": {"path":menu_03, "text":"Cucumber Juice"},
      "title": "Cucumber Juice",
      "description": "A classic Cucumber Juice with a modern twist.",
      "price": 11.99,
      "badge": "NEW",
      "tag": "drinks",
    },
    {
      "id": 12,
      "image": {"path":menu_02, "text":"Baby Burguer"},
      "title": "Baby Burguer",
      "description": "Flavorful Baby Burguer with a hint of spice.",
      "price": 12.99,
      "badge": "HOT",
      "tag":"nonveg",
    },
    {
      "id": 13,
      "image": {"path":menu_06, "text":"Greek Moussaka"},
      "title": "Greek Moussaka",
      "description": "A delicious Greek Moussaka made with fresh ingredients.",
      "price": 8.99,
      "badge": null,
      "tag":"vegetarian"
    },
    {
      "id": 14,
      "image": {"path":menu_07, "text":"Hot Dog"},
      "title": "Hot Dog",
      "description": "A savory Hot Dog with a burst of flavors.",
      "price": 10.99,
      "badge": null,
      "tag": "starters",
    },
    {
      "id": 15,
      "image": {"path":menu_01, "text":"Chicken Parmesan"},
      "title": "Chicken Parmesan",
      "description": "A delightful Chicken Parmesan that will leave you wanting more.",
      "price": 13.99,
      "badge": "NEW",
      "tag": "starters",
    },
    {
      "id": 16,
      "image": {"path":menu_04, "text":"Kiwi Frozen Yogurt"},
      "title": "Kiwi Frozen Yogurt",
      "description": "Mouthwatering Kiwi Frozen Yogurt that combines different tastes.",
      "price": 15.99,
      "badge": "HOT",
      "tag": "dessert",
    },
    {
      "id": 17,
      "image": {"path":menu_07, "text":"Hot Dog"},
      "title": "Hot Dog",
      "description": "A fusion Hot Dog with unique flavors.",
      "price": 11.99,
      "badge": null,
      "tag": "starters",
    },
    {
      "id": 18,
      "image": {"path":menu_01, "text":"Chicken Parmesan"},
      "title": "Chicken Parmesan",
      "description": "A comforting Chicken Parmesan to warm your soul.",
      "price": 9.99,
      "badge": null,
      "tag": "dessert",
    },
    {
      "id": 19,
      "image": {"path":menu_02, "text":"Baby Burguer"},
      "title": "Baby Burguer",
      "description": "Exquisite Baby Burguer with a touch of luxury.",
      "price": 16.99,
      "badge": "NEW",
      "tag":"vegetarian",
    },
    {
      "id": 20,
      "image": {"path":menu_06, "text":"Greek Moussaka"},
      "title": "Greek Moussaka",
      "description": "A zesty Greek Moussaka with a tangy twist.",
      "price": 10.99,
      "badge": null,
      "tag":"drinks"
    },
    {
      "id": 21,
      "image": {"path":menu_08, "text":"Patatas Rellenas"},
      "title": "Patatas Rellenas",
      "description": "A light Patatas Rellenas that is perfect for lunch.",
      "price": 9.99,
      "badge": null,
      "tag":"starters"
    },
    {
      "id": 22,
      "image": {"path":menu_04, "text":"Kiwi Frozen Yogurt"},
      "title": "Kiwi Frozen Yogurt",
      "description": "Satisfying Kiwi Frozen Yogurt with a touch of elegance.",
      "price": 14.99,
      "badge": null,
      "tag": "dessert",
    },
    {
      "id": 23,
      "image": {"path":menu_06, "text":"Greek Moussaka"},
      "title": "Greek Moussaka",
      "description": "A classic Greek Moussaka with a modern twist.",
      "price": 11.99,
      "badge": "NEW",
      "tag":"drinks"
    },
    {
      "id": 24,
      "image": {"path":menu_02, "text":"Baby Burguer"},
      "title": "Baby Burguer",
      "description": "Flavorful Baby Burguer with a hint of spice.",
      "price": 12.99,
      "badge": "HOT",
      "tag":"dessert",
    },
    {
      "id": 25,
      "image": {"path":menu_05, "text":"Grilled Salmon"},
      "title": "Grilled Salmon",
      "description": "A delicious Grilled Salmon made with fresh ingredients.",
      "price": 8.99,
      "badge": null,
      "tag": "vegetarian",
    },
    {
      "id": 26,
      "image": {"path":menu_01, "text":"Chicken Parmesan"},
      "title": "Chicken Parmesan",
      "description": "A savory Chicken Parmesan with a burst of flavors.",
      "price": 10.99,
      "badge": null,
      "tag": "dessert",
    },
    {
      "id": 27,
      "image": {"path":menu_07, "text":"Hot Dog"},
      "title": "Hot Dog",
      "description": "A delightful Hot Dog that will leave you wanting more.",
      "price": 13.99,
      "badge": "NEW",
      "tag": "starters",
    },
    {
      "id": 28,
      "image": {"path":menu_03, "text":"Cucumber Juice"},
      "title": "Cucumber Juice",
      "description": "Mouthwatering Cucumber Juice that combines different tastes.",
      "price": 15.99,
      "badge": "HOT",
      "tag": "drinks",
    },
    {
      "id": 29,
      "image": {"path":menu_06, "text":"Greek Moussaka"},
      "title": "Greek Moussaka",
      "description": "A fusion Greek Moussaka with unique flavors.",
      "price": 11.99,
      "badge": null,
      "tag":"vegetarian"
    },
    {
      "id": 30,
      "image": {"path":menu_02, "text":"Baby Burguer"},
      "title": "Baby Burguer",
      "description": "A comforting Baby Burguer to warm your soul.",
      "price": 9.99,
      "badge": null,
      "tag":"vegetarian",
    },
    {
      "id": 31,
      "image": {"path":menu_08, "text":"Patatas Rellenas"},
      "title": "Patatas Rellenas",
      "description": "Exquisite Patatas Rellenas with a touch of luxury.",
      "price": 16.99,
      "badge": "NEW",
      "tag":"vegetarian",
    },
    {
      "id": 32,
      "image": {"path":menu_08, "text":"Patatas Rellenas"},
      "title": "Patatas Rellenas",
      "description": "A light Patatas Rellenas that is perfect for lunch.",
      "price": 9.99,
      "badge": null,
      "tag":"nonveg",
    },
    {
      "id": 33,
      "image": {"path":menu_06, "text":"Greek Moussaka"},
      "title": "Greek Moussaka",
      "description": "Satisfying Greek Moussaka with a touch of elegance.",
      "price": 14.99,
      "badge": null,
      "tag":"vegetarian",
    },
    {
      "id": 34,
      "image": {"path":menu_03, "text":"Cucumber Juice"},
      "title": "Cucumber Juice",
      "description": "A classic Cucumber Juice with a modern twist.",
      "price": 11.99,
      "badge": "NEW",
      "tag": "drinks",
    },
    {
      "id": 35,
      "image": {"path":menu_02, "text":"Baby Burguer"},
      "title": "Baby Burguer",
      "description": "Flavorful Baby Burguerwith a hint of spice.",
      "price": 12.99,
      "badge": "HOT",
      "tag":"nonveg",
    },
    {
      "id": 36,
      "image": {"path":menu_07, "text":"Hot Dog"},
      "title": "Hot Dog",
      "description": "A delicious Hot Dog made with fresh ingredients.",
      "price": 8.99,
      "badge": null,
      "tag": "starters",
    },
    {
      "id": 37,
      "image": {"path":menu_01, "text":"Chicken Parmesan"},
      "title": "Chicken Parmesan",
      "description": "A savory Chicken Parmesan with a burst of flavors.",
      "price": 10.99,
      "badge": null,
      "tag": "drinks",
    },
    {
      "id": 38,
      "image": {"path":menu_04, "text":"Kiwi Frozen Yogurt"},
      "title": "Kiwi Frozen Yogurt",
      "description": "A delightful Kiwi Frozen Yogurt that will leave you wanting more.",
      "price": 13.99,
      "badge": "NEW",
      "tag": "dessert",
    },
    {
      "id": 39,
      "image": {"path":menu_08, "text":"Patatas Rellenas"},
      "title": "Patatas Rellenas",
      "description": "Mouthwatering Patatas Rellenas that combines different tastes.",
      "price": 15.99,
      "badge": "HOT",
      "tag": "starters"
    },
    {
      "id": 40,
      "image": {"path":menu_01, "text":"Grilled Salmon"},
      "title": "Grilled Salmon",
      "description": "A fusion Grilled Salmon with unique flavors.",
      "price": 11.99,
      "badge": null,
      "tag": "drinks",
    },
  ],
};
