import menu_01 from "../assets/menu/menu_01.jpg";
import menu_02 from "../assets/menu/menu_02.jpg";
import menu_03 from "../assets/menu/menu_03.jpg";
import menu_04 from "../assets/menu/menu_04.jpg";
import menu_05 from "../assets/menu/menu_05.jpg";
import menu_06 from "../assets/menu/menu_06.jpg";
import menu_07 from "../assets/menu/menu_07.jpg";
import menu_08 from "../assets/menu/menu_08.jpg";

export const menu = {
  "menuData":[{
      "id": 1,
      "image": {"path":menu_01, "text":"Chicken Parmesan"},
      "title": "Chicken Parmesan",
      "description": "Deliciously indulgent dish bursting with unique flavors.",
      "price": 9.99,
      "badge": "NEW",
      "tag": "nonveg",
    },
    {
      "id": 2,
      "image": {"path":menu_02, "text":"Baby Burguer"},
      "title": "Baby Burguer",
      "description": "Deliciously indulgent dish bursting with unique flavors.",
      "price": 12.99,
      "badge": "HOT",
      "tag":"nonveg",
    },
    {
      "id": 3,
      "image": {"path":menu_03, "text":"Cucumber Juice"},
      "title": "Cucumber Juice",
      "description": "Deliciously indulgent dish bursting with unique flavors.",
      "price": 8.99,
      "badge": null,
      "tag": "drinks",
    },
    {
      "id": 4,
      "image": {"path":menu_04, "text":"Kiwi Frozen Yogurt"},
      "title": "Kiwi Frozen Yogurt",
      "description": "Deliciously indulgent dish bursting with unique flavors.",
      "price": 14.99,
      "badge": "NEW",
      "tag": "dessert",
    },
    {
      "id": 5,
      "image": {"path":menu_05, "text":"Grilled Salmon"},
      "title": "Grilled Salmon",
      "description": "Deliciously indulgent dish bursting with unique flavors.",
      "price": 10.99,
      "badge": null,
      "tag": "nonveg",
    },
    {
      "id": 6,
      "image": {"path":menu_06, "text":"Greek Moussaka"},
      "title": "Greek Moussaka",
      "description": "Deliciously indulgent dish bursting with unique flavors.",
      "price": 11.99,
      "badge": "HOT",
      "tag":"vegetarian"
    },
    {
      "id": 7,
      "image": {"path":menu_07, "text":"Hot Dog"},
      "title": "Hot Dog",
      "description": "Deliciously indulgent dish bursting with unique flavors.",
      "price": 13.99,
      "badge": null,
      "tag": "starters",
    },
    {
      "id": 8,
      "image": {"path":menu_08, "text":"Patatas Rellenas"},
      "title": "Patatas Rellenas",
      "description": "Deliciously indulgent dish bursting with unique flavors.",
      "price": 9.99,
      "badge": "NEW",
      "tag": "nonveg",
    },
    {
      "id": 9,
      "image": {"path":menu_04, "text":"Kiwi Frozen Yogurt"},
      "title": "Kiwi Frozen Yogurt",
      "description": "Deliciously indulgent dish bursting with unique flavors.",
      "price": 9.99,
      "badge": null,
      "tag": "dessert",
    },
    {
      "id": 10,
      "image": {"path":menu_05, "text":"Grilled Salmon"},
      "title": "Grilled Salmon",
      "description": "Deliciously indulgent dish bursting with unique flavors.",
      "price": 14.99,
      "badge": null,
      "tag": "nonveg",
    },
    {
      "id": 11,
      "image": {"path":menu_03, "text":"Cucumber Juice"},
      "title": "Cucumber Juice",
      "description": "Deliciously indulgent dish bursting with unique flavors.",
      "price": 11.99,
      "badge": "NEW",
      "tag": "drinks",
    },
    {
      "id": 12,
      "image": {"path":menu_02, "text":"Baby Burguer"},
      "title": "Baby Burguer",
      "description": "Deliciously indulgent dish bursting with unique flavors.",
      "price": 12.99,
      "badge": "HOT",
      "tag":"nonveg",
    },
    {
      "id": 13,
      "image": {"path":menu_06, "text":"Greek Moussaka"},
      "title": "Greek Moussaka",
      "description": "Deliciously indulgent dish bursting with unique flavors.",
      "price": 8.99,
      "badge": null,
      "tag":"vegetarian"
    },
    {
      "id": 14,
      "image": {"path":menu_07, "text":"Hot Dog"},
      "title": "Hot Dog",
      "description": "Deliciously indulgent dish bursting with unique flavors.",
      "price": 10.99,
      "badge": null,
      "tag": "starters",
    },
    {
      "id": 15,
      "image": {"path":menu_01, "text":"Chicken Parmesan"},
      "title": "Chicken Parmesan",
      "description": "Deliciously indulgent dish bursting with unique flavors.",
      "price": 13.99,
      "badge": "NEW",
      "tag": "starters",
    },
    {
      "id": 16,
      "image": {"path":menu_04, "text":"Kiwi Frozen Yogurt"},
      "title": "Kiwi Frozen Yogurt",
      "description": "Deliciously indulgent dish bursting with unique flavors.",
      "price": 15.99,
      "badge": "HOT",
      "tag": "dessert",
    },
    {
      "id": 17,
      "image": {"path":menu_07, "text":"Hot Dog"},
      "title": "Hot Dog",
      "description": "Deliciously indulgent dish bursting with unique flavors.",
      "price": 11.99,
      "badge": null,
      "tag": "starters",
    },
    {
      "id": 18,
      "image": {"path":menu_01, "text":"Chicken Parmesan"},
      "title": "Chicken Parmesan",
      "description": "Deliciously indulgent dish bursting with unique flavors.",
      "price": 9.99,
      "badge": null,
      "tag": "dessert",
    },
    {
      "id": 19,
      "image": {"path":menu_02, "text":"Baby Burguer"},
      "title": "Baby Burguer",
      "description": "Deliciously indulgent dish bursting with unique flavors.",
      "price": 16.99,
      "badge": "NEW",
      "tag":"vegetarian",
    },
    {
      "id": 20,
      "image": {"path":menu_06, "text":"Greek Moussaka"},
      "title": "Greek Moussaka",
      "description": "Deliciously indulgent dish bursting with unique flavors.",
      "price": 10.99,
      "badge": null,
      "tag":"drinks"
    },
    {
      "id": 21,
      "image": {"path":menu_08, "text":"Patatas Rellenas"},
      "title": "Patatas Rellenas",
      "description": "Deliciously indulgent dish bursting with unique flavors.",
      "price": 9.99,
      "badge": null,
      "tag":"starters"
    },
    {
      "id": 22,
      "image": {"path":menu_04, "text":"Kiwi Frozen Yogurt"},
      "title": "Kiwi Frozen Yogurt",
      "description": "Deliciously indulgent dish bursting with unique flavors.",
      "price": 14.99,
      "badge": null,
      "tag": "dessert",
    },
    {
      "id": 23,
      "image": {"path":menu_06, "text":"Greek Moussaka"},
      "title": "Greek Moussaka",
      "description": "Deliciously indulgent dish bursting with unique flavors.",
      "price": 11.99,
      "badge": "NEW",
      "tag":"drinks"
    },
    {
      "id": 24,
      "image": {"path":menu_02, "text":"Baby Burguer"},
      "title": "Baby Burguer",
      "description": "Deliciously indulgent dish bursting with unique flavors.",
      "price": 12.99,
      "badge": "HOT",
      "tag":"dessert",
    },
    {
      "id": 25,
      "image": {"path":menu_05, "text":"Grilled Salmon"},
      "title": "Grilled Salmon",
      "description": "Deliciously indulgent dish bursting with unique flavors.",
      "price": 8.99,
      "badge": null,
      "tag": "vegetarian",
    },
    {
      "id": 26,
      "image": {"path":menu_01, "text":"Chicken Parmesan"},
      "title": "Chicken Parmesan",
      "description": "Deliciously indulgent dish bursting with unique flavors.",
      "price": 10.99,
      "badge": null,
      "tag": "dessert",
    },
    {
      "id": 27,
      "image": {"path":menu_07, "text":"Hot Dog"},
      "title": "Hot Dog",
      "description": "Deliciously indulgent dish bursting with unique flavors.",
      "price": 13.99,
      "badge": "NEW",
      "tag": "starters",
    },
    {
      "id": 28,
      "image": {"path":menu_03, "text":"Cucumber Juice"},
      "title": "Cucumber Juice",
      "description": "Deliciously indulgent dish bursting with unique flavors.",
      "price": 15.99,
      "badge": "HOT",
      "tag": "drinks",
    },
    {
      "id": 29,
      "image": {"path":menu_06, "text":"Greek Moussaka"},
      "title": "Greek Moussaka",
      "description": "Deliciously indulgent dish bursting with unique flavors.",
      "price": 11.99,
      "badge": null,
      "tag":"vegetarian"
    },
    {
      "id": 30,
      "image": {"path":menu_02, "text":"Baby Burguer"},
      "title": "Baby Burguer",
      "description": "Deliciously indulgent dish bursting with unique flavors.",
      "price": 9.99,
      "badge": null,
      "tag":"vegetarian",
    },
    {
      "id": 31,
      "image": {"path":menu_08, "text":"Patatas Rellenas"},
      "title": "Patatas Rellenas",
      "description": "Deliciously indulgent dish bursting with unique flavors.",
      "price": 16.99,
      "badge": "NEW",
      "tag":"vegetarian",
    },
    {
      "id": 32,
      "image": {"path":menu_08, "text":"Patatas Rellenas"},
      "title": "Patatas Rellenas",
      "description": "Deliciously indulgent dish bursting with unique flavors.",
      "price": 9.99,
      "badge": null,
      "tag":"nonveg",
    },
    {
      "id": 33,
      "image": {"path":menu_06, "text":"Greek Moussaka"},
      "title": "Greek Moussaka",
      "description": "Deliciously indulgent dish bursting with unique flavors.",
      "price": 14.99,
      "badge": null,
      "tag":"vegetarian",
    },
    {
      "id": 34,
      "image": {"path":menu_03, "text":"Cucumber Juice"},
      "title": "Cucumber Juice",
      "description": "Deliciously indulgent dish bursting with unique flavors.",
      "price": 11.99,
      "badge": "NEW",
      "tag": "drinks",
    },
    {
      "id": 35,
      "image": {"path":menu_02, "text":"Baby Burguer"},
      "title": "Baby Burguer",
      "description": "Deliciously indulgent dish bursting with unique flavors.",
      "price": 12.99,
      "badge": "HOT",
      "tag":"nonveg",
    },
    {
      "id": 36,
      "image": {"path":menu_07, "text":"Hot Dog"},
      "title": "Hot Dog",
      "description": "Deliciously indulgent dish bursting with unique flavors.",
      "price": 8.99,
      "badge": null,
      "tag": "starters",
    },
    {
      "id": 37,
      "image": {"path":menu_01, "text":"Chicken Parmesan"},
      "title": "Chicken Parmesan",
      "description": "Deliciously indulgent dish bursting with unique flavors.",
      "price": 10.99,
      "badge": null,
      "tag": "drinks",
    },
    {
      "id": 38,
      "image": {"path":menu_04, "text":"Kiwi Frozen Yogurt"},
      "title": "Kiwi Frozen Yogurt",
      "description": "Deliciously indulgent dish bursting with unique flavors.",
      "price": 13.99,
      "badge": "NEW",
      "tag": "dessert",
    },
    {
      "id": 39,
      "image": {"path":menu_08, "text":"Patatas Rellenas"},
      "title": "Patatas Rellenas",
      "description": "Deliciously indulgent dish bursting with unique flavors.",
      "price": 15.99,
      "badge": "HOT",
      "tag": "starters"
    },
    {
      "id": 40,
      "image": {"path":menu_01, "text":"Grilled Salmon"},
      "title": "Grilled Salmon",
      "description": "Deliciously indulgent dish bursting with unique flavors.",
      "price": 11.99,
      "badge": null,
      "tag": "drinks",
    },
  ],
};
